TASK-added-http-client-mtd
crazilazi/MRI.DataLake.Search.API pull request #16
Opened 2023-04-07 10:10 UTC by mandy-0698

2023-04-07 10:21 UTC, nandishss commented
- Updated for http client
- Using the query to get result and returning it
- Rebased with develop

2023-04-07 10:39 UTC, nandishss requested changes

2023-04-07 10:39 UTC, nandishss commented on Controllers/DataLakeSearchController.cs
> +    public async Task<dynamic> GetTableInformation(string tableName)
change it to IActionResult

2023-04-07 10:39 UTC, nandishss commented on Repositories/DataLakeSearchRepositories.cs
> +                string sql = query;
remove it

2023-04-10 03:20 UTC, nandishss approved these changes

2023-04-10 03:54 UTC, Vani-H-Umesh approved these changes

2023-04-10 05:00 UTC, merged